[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
num = "0.4.0"
image = { version = "0.24.6", features = ["png"] }
scarlet = "1.1.0"
colorous = "1.0.10"
